export 'package:flutter/material.dart';
export 'package:flutter_screenutil/flutter_screenutil.dart';
export 'package:get/get.dart' hide FormData, MultipartFile, Response;
// export 'src/src.dart';
export 'package:pin_code_fields/pin_code_fields.dart';
export 'package:flutter_rating_bar/flutter_rating_bar.dart';
// export 'package:dio/dio.dart';
// export 'package:hotelseatbooking/global/global_variable.dart';
// export 'package:dio_http2_adapter/dio_http2_adapter.dart';
// export 'package:hotelseatbooking/global/global_function.dart';
// export 'package:hotelseatbooking/api_service/api_service.dart';
// export 'package:hotelseatbooking/app_sharepreference/app_sharepreference.dart';
// //Icon

// export 'package:fluttericon/brandico_icons.dart';
// export 'package:fluttericon/elusive_icons.dart';
// export 'package:fluttericon/entypo_icons.dart';
// export 'package:fluttericon/font_awesome5_icons.dart';
// export 'package:fluttericon/font_awesome_icons.dart';
// export 'package:fluttericon/fontelico_icons.dart';
// export 'package:fluttericon/iconic_icons.dart';
// export 'package:fluttericon/linearicons_free_icons.dart';
// export 'package:fluttericon/linecons_icons.dart';
// export 'package:fluttericon/maki_icons.dart';
// export 'package:fluttericon/meteocons_icons.dart';
// export 'package:fluttericon/mfg_labs_icons.dart';
// export 'package:fluttericon/modern_pictograms_icons.dart';
// export 'package:fluttericon/octicons_icons.dart';
// export 'package:fluttericon/rpg_awesome_icons.dart';
// export 'package:fluttericon/typicons_icons.dart';
// export 'package:fluttericon/web_symbols_icons.dart';
// export 'package:fluttericon/zocial_icons.dart';
export 'package:shared_preferences/shared_preferences.dart';
